import type { NextPage } from 'next';
import Link from 'next/link';
import moment from 'moment';
import Head from 'next/head';
import { Box, Button, Center, Image, Text } from '@chakra-ui/react';
import { AddIcon, ArrowBackIcon, CalendarIcon, StarIcon } from '@chakra-ui/icons';
import styles from '../../styles/Home.module.css';
import { GoLocation } from 'react-icons/go';
import { assets } from '../../constants/assets';

const Home: NextPage = () => {
  return (
    <Center className={`${styles.container} ${styles.bg}`} style={{ border: 'none' }}>
      <Head>
        <title>Fuego Group App 🔥</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box style={{ width: '950px', position: 'relative' }}>
        <Box className={styles.imageBox}>
          <Box
            style={{
              position: 'absolute',
              bottom: '120px',
              display: 'flex',
              flexDirection: 'column',
              flex: 1
            }}
          >
            <Text
              style={{
                fontSize: '30px',
                fontWeight: 'bold',
                color: '#fffff',
                textShadow: '2px 2px 4px #000000'
              }}
              className={styles.matchTitle}
            >
              CV Fuego vs Oakland Roots
            </Text>
            <Text
              style={{
                fontSize: '12px',
                fontWeight: 'bold',
                color: '#fffff',
                textShadow: '2px 2px 4px #000000'
              }}
              className={styles.matchT}
            >
              <span style={{ padding: '5px' }}>
                <CalendarIcon />
              </span>
              {assets.matchDate}
            </Text>
            <Text
              style={{
                fontSize: '12px',
                fontWeight: 'bold',
                color: '#fffff',
                textShadow: '2px 2px 4px #000000',
                display: 'inline-flex'
              }}
              className={styles.matchT}
            >
              <span style={{ padding: '5px' }}>
                <GoLocation />
              </span>
              {assets.matchDate}
            </Text>
          </Box>
        </Box>

        <Box
          style={{
            borderRadius: '15px',
            backgroundColor: 'white',
            position: 'absolute',
            top: '200px',
            width: '950px'
          }}
          p='12'
        >
          <Box
            mt='1'
            fontWeight='semibold'
            as='h4'
            fontSize={'2xl'}
            lineHeight='tight'
            isTruncated
            textAlign={'center'}
          >
            {assets.ticketTitle}
          </Box>

          <Box textAlign={'left'} fontSize={'sm'} p={3}>
            {assets.ticketDescription}
          </Box>

          <Box m='5'>
            <Image
              src={assets.stadiumChart}
              alt={assets.stadiumAlt}
              style={{ height: '250px', margin: 'auto' }}
            />
          </Box>
          <Box>
            <Link href={'/purchase/'} passHref>
              <Button
                style={{
                  width: '40px',
                  height: '40px',
                  padding: '20.3px 20.3px',
                  borderRadius: '50%',
                  backgroundColor: '#c91a18',
                  color: '#fff',
                  border: 'solid 1px #e5eeff',
                  cursor: 'pointer',
                  alignItems: 'center'
                }}
              >
                <ArrowBackIcon />
              </Button>
            </Link>
          </Box>
        </Box>
      </Box>
    </Center>
  );
};

export default Home;
